//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4333
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableLaba2
    {
        public string ФИО { get; set; }
        public int Код_клиента { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public int Индекс { get; set; }
        public string Город { get; set; }
        public string Улица { get; set; }
        public int Дом { get; set; }
        public int Квартира { get; set; }
        public string E_mail { get; set; }
        public int Возраст { get; set; }
    }
}
